### ISSUE TITLE
getCharacterCount is deprecated. remove useEditorCharacterCount

### ISSUE THREAD

**Issue by amirhhashemi** [lxsmnsyc/solid-tiptap#6]
The `getCharacterCount` function is deprecated and its functionality is moved to a separate extension. So the `useEditorCharacterCount` function should be removed. It's a breaking change, you might want to do it when you are ready to do a major release

**Comment by lxsmnsyc** [comment]
Yeah I really need to check for the recent changes. Didn't Tiptap already release a stable version?

**Comment by amirhhashemi** [comment]
Yeah, the v2 finally stabilized a few days ago
